#!/bin/bash

CON=http://consul.service.consul:8500/v1/kv/${CLUSTERNAME}
sleep 1
host ${CONSUL_HOST} >/dev/null 2>&1
if [ $? -eq 0 ]; then
	curl -X PUT ${CON}/clustername -d ${CLUSTERNAME} 
	curl -X PUT ${CON}/data -d ${DATA} 
	curl -X PUT ${CON}/port -d ${PORT}
	curl -X PUT ${CON}/expected_nodes -d ${EXPECTED_NODES}
	curl -X PUT ${CON}/version -d ${ES_VER}
	sleep 1
	/bin/consul-template \
		-consul ${CONSUL_HOST}:8500 \
		-template "/templates/elasticsearch.yml.ctmpl:/usr/local/elasticsearch/config/elasticsearch.yml" \
		-retry 30s \
		-once 
fi

exec "$@"