################################### Cluster ###################################

cluster.name: elasticsearch-cluster

#################################### Node #####################################

node.name: elasticsearch-node
node.max_local_storage_nodes: 1

#################################### Index ####################################

index.mapper.dynamic: true
action.auto_create_index: false
action.disable_delete_all_indices: true

#################################### Paths ####################################

path.conf: /usr/share/elasticsearch/config
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch

#################################### Plugin ###################################


################################### Memory ####################################

bootstrap.mlockall: true

############################## Network And HTTP ###############################

http.port: 9200

################################### Gateway ###################################

gateway.expected_nodes: 1

############################# Recovery Throttling #############################


################################## Discovery ##################################


################################## Slow Log ###################################


################################## GC Logging #################################


################################## JMX ########################################


################################## Custom #####################################

node.data: true
network.host: 0.0.0.0
action.auto_create_index: false
script.disable_dynamic: false
