################################### Cluster ###################################

cluster.name: elasticsearch-cluster

#################################### Node #####################################

node.name: elasticsearch-node
node.max_local_storage_nodes: 1

#################################### Index ####################################

index.mapper.dynamic: true
action.auto_create_index: true
action.disable_delete_all_indices: true

#################################### Paths ####################################

path.conf: /usr/local/elasticsearch
path.data: /data
path.logs: /var/log/elasticsearch

#################################### Plugin ###################################


################################### Memory ####################################

bootstrap.mlockall: true

############################## Network And HTTP ###############################

http.port: 9200

################################### Gateway ###################################

gateway.expected_nodes: 1

############################# Recovery Throttling #############################


################################## Discovery ##################################

discovery.zen.ping.multicast.enable: false

################################## Slow Log ###################################


################################## GC Logging #################################


################################## JMX ########################################


################################## Custom #####################################

action.auto_create_index: false
node.data: true
script.disable_dynamic: false

